### PR TITLE
Update to new global generator CubeMX concept

### PR DESCRIPTION
**Pull request by DavidLesnjak**

### CODE REVIEW

**Comment by jkrech** [comment]
I suggest to merge this PR, despite the fact that Solar might not be able to import it. 
I do not expect this example to work immediately in Keil Studio Cloud, as it is outdated and does not use the latest CMSIS build service using CMSIS-Toolbox 2.6.1

**Review by jkrech — APPROVED** [review]
LGTM

**Review by KeilChris — APPROVED** [review]
I agree, let's get this out the door.

**Comment by acabarbaye** [comment]
@jkrech @KeilChris The action is not just about KSC though as it publishes the example to keil.arm.com. The action has now been updated with latest CMSIS tools and schemas and the problem is because one of the files does not comply with schema:     - /job-cache/RTE/CMSIS/RTX_Config.h (base@5.6.0) hello.cbuild-pack.yml - file is already up-to-date hello.Release+B-U585I-IOT02A.cbuild.yml - file generated successfully]] project:hello]] cdefault:cdefault.yml cprojects:[map[cproject:hello.cproject.yml]] csolution:hello.csolution.yml description:Simple Hello World example for B-U585I-IOT02A generated-by:csolution version 2.6.0 tmpdir:tmp]]] against schema: jsonschema: '/build-idx/cbuilds/0' does not validate with https://raw.githubusercontent.com/Open-CMSIS-Pack/devtools/schemas/projmgr/2.4.0/tools/projmgr/schemas/cbuild-idx.schema.json#/properties/build-idx/$ref/properties/cbuilds/$ref/items/$ref/additionalProperties: additionalProperties 'messages' not allowed

**Comment by acabarbaye** [comment]
I can look why the version 2.6.0 has not been selected since I definitely upgraded them but this would not remove the underlying schema problem: the generated files seem to have a `messages` entry which is not allowed by the schema definition because of `additionalProperties: false`

**Comment by brondani** [comment]
Actually `messages` are allowed in the schema 2.6.0:
https://github.com/Open-CMSIS-Pack/devtools/blob/schemas/projmgr/2.6.0/tools/projmgr/schemas/common.schema.json#L963

**Pull request merged**
